export * from "./Home";
export * from "./Profile";
export * from "./ESim";
export * from "./FbLogo";
export * from "./LinkSvg";
export * from "./SimfreeLogo";
export * from "./ShareSvg";
export * from "./LogoSvg";
export * from "./GiftIcon";
